# Generated by Django 4.2.11 on 2024-05-20 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "attachment",
                    models.FileField(
                        upload_to="attachment/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.FloatField(null=True)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="UK", max_length=2, verbose_name="country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Control_Question",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("control_question", models.TextField()),
                ("line_number", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["line_number"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("IT", "Information Technology"),
                            ("Finance", "Finance"),
                            ("Healthcare", "Healthcare"),
                            ("Manufacturing", "Manufacturing"),
                            ("Retail", "Retail"),
                            ("Real Estate", "Real Estate"),
                            ("Education", "Education"),
                            ("Transportation", "Transportation"),
                            ("Hospitality", "Hospitality"),
                            ("Energy", "Energy"),
                            ("Entertainment", "Entertainment"),
                            ("Agriculture", "Agriculture"),
                            ("Telecommunications", "Telecommunications"),
                            ("Automotive", "Automotive"),
                            ("Construction", "Construction"),
                            ("Media", "Media"),
                            ("Pharmaceuticals", "Pharmaceuticals"),
                            ("Government", "Government"),
                            ("Non-Profit", "Non-Profit"),
                            ("Fashion", "Fashion"),
                            ("Consulting", "Consulting"),
                            ("Insurance", "Insurance"),
                            ("Legal", "Legal"),
                            ("Advertising", "Advertising"),
                            ("Banking", "Banking"),
                            ("Biotechnology", "Biotechnology"),
                            ("Chemical", "Chemical"),
                            ("Computer", "Computer"),
                            ("Defense", "Defense"),
                            ("Electronics", "Electronics"),
                            ("Energy", "Energy"),
                            ("Food", "Food"),
                            ("Healthcare", "Healthcare"),
                            ("Information", "Information"),
                            ("Insurance", "Insurance"),
                            ("Legal", "Legal"),
                            ("Manufacturing", "Manufacturing"),
                            ("Media", "Media"),
                            ("Mining", "Mining"),
                            ("Pharmaceuticals", "Pharmaceuticals"),
                            ("Real Estate", "Real Estate"),
                            ("Retail", "Retail"),
                            ("Software", "Software"),
                            ("Technology", "Technology"),
                            ("Telecommunications", "Telecommunications"),
                            ("Transportation", "Transportation"),
                            ("other", "other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("ongoing evaluation", "Ongoing Evaluation"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                            ("active", "Active"),
                            ("scheme in progress", "Scheme In Progress"),
                            ("completed scheme", "Completed Scheme"),
                            (
                                "completed scheme & test plan",
                                "Completed Scheme & Test Plan",
                            ),
                            ("full", "Full"),
                            ("partial", "Partial"),
                            ("falied", "Falied"),
                            ("passed", "Passed"),
                            ("pending", "Pending"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test_Case",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=25)),
                ("description", models.TextField()),
                ("recommendation", models.TextField()),
                ("note", models.TextField()),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.attachment",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.control_question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("system_information", models.TextField()),
                ("security_concern", models.TextField()),
                ("description", models.TextField()),
                (
                    "status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.status"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Security_Vulnerability",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("likelihood", models.IntegerField()),
                ("impact", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Security_Requirement",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("weight", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
