# Generated by Django 4.2.11 on 2024-05-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.attachment",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.client",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="domain",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.domain",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sector",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.sector",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.status",
            ),
        ),
        migrations.AddField(
            model_name="control_question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.category"
            ),
        ),
    ]
